### ISSUE TITLE
The ID numbers are in a random order

### ISSUE THREAD

**Issue by ashleygwilliams** [bostonjs/bostonjs.com#13]
The ID numbers displayed on the home page come from Nest. But the order they were added to nest seems to have been random, so on the home page it looks random.

There are at least two possible solutions:

1. Ignore the Nest IDs and generate the IDs during the compilation step
2. Wipe the nest database and update the build step to input them in nest in chronological order

**Comment by Wilto** [comment]
This is okay to close out, yeah?

**Comment by ajpiano** [comment]
Yep
