### ISSUE TITLE
styling for form

### ISSUE THREAD

**Issue by ashleygwilliams** [bostonjs/bostonjs.com#14]

**Comment by Wilto** [comment]
Leaving this one open; likely going to tweak the design on this a little

**Comment by Wilto** [comment]
Okay, got an idea for this. I kinda dig doing the inputs as just underlines, but they weren’t immediately recognizable as inputs. So, maybe something like:

![image](https://cloud.githubusercontent.com/assets/439942/6759817/8d6f1f92-cf19-11e4-8e59-e034a363f5cf.png)

And then when text has been entered, we can drop that background:

![image](https://cloud.githubusercontent.com/assets/439942/6759807/733956c4-cf19-11e4-8a19-dfe2b38fa1f8.png)

What do we think? @isaacdurazo?

**Comment by ajpiano** [comment]
this looks hella tight

**Comment by isaacdurazo** [comment]
I like the style but I think it's too much yellow. I'd rather use some shades of gray to complement the yellow, maybe?

![screen shot 2015-03-20 at 1 04 38 pm](https://cloud.githubusercontent.com/assets/1379244/6759967/b84e77d4-cf01-11e4-884a-b662e7789234.png)

**Comment by Wilto** [comment]
Oh, nice. Sold.
